algoritmo "semnome"
var
   idade,valor:inteiro
inicio
      EscrevaL ("-------------------")
      EscrevaL ("Sua idade é:  ")
      EscrevaL ("[1] Menos que 18")
      EscrevaL ("[2] Mais que 18")
      EscrevaL ("[3] Mais que 60")
      Escreva (":")
      Leia (valor)
      Escolha (valor)
      Caso 1
      Escreva ("CRIANÇÂO")
      Caso 2
      Escreva ("UIUI, ADULTINHO")
      Caso 3
      Escreva ("VELHO MALDITO")
      Fimescolha
fimalgoritmo