algoritmo "semnome"
var
   x,y,n1,n2:real
procedimento soma (a,b:real)
inicio
             EscrevaL (" Recebi o valor", a)
             EscrevaL (" Recebi o valor", b)
             EscrevaL (" A soma entre os dois é", a+b)
Fimprocedimento
inicio
      Escreva ("Digite um número:")
      leia (n1)
      Escreva ("Digite outro número:")
      Leia (n2)
      x <- n1
      y <- n2
      soma (x,y)

fimalgoritmo